language: php
cache:
  directories:
  - "$HOME/.composer/cache"
php:
  - '7.2'
script:
- vendor/bin/phpunit -c phpunit.xml
- vendor/bin/phpunit --coverage-clover=coverage.xml

install: composer install --no-interaction
