version: 2
jobs:
  build:
    branches:
      only:
        - dev
        - master
    docker:
      - image: circleci/php:7-fpm-browsers-legacy
    steps:
      - checkout
      - run: apt-get update && apt-get install -y \
                  libfreetype6-dev \
                  libjpeg62-turbo-dev \
                  libpng-dev \
              && docker-php-ext-install -j$(nproc) json
      - run:
          name: "install composer dependency"
          command: composer install
      - run:
          name: "Run tests"
          command: phpdbg -d memory_limit=512M -qrr vendor/bin/phpunit --coverage-html build/coverage-report
      - store_artifacts:
          path:  build/coverage-report
